public class Main {
    public static void main(String[] args) {
        System.out.println("Домашнее задание.");
        System.out.println("Задача 1.");
        int a = 1234599;
        System.out.println(a);
        System.out.println("Значение переменной a" + " с типом int" + " равно " + a);
        byte me = 1;
        System.out.println(me);
        System.out.println("Значение переменной me" + " с типом byte" + " равно " + me);
        short youCool = 31898;
        System.out.println(youCool);
        System.out.println("Значение переменной youCool" + " с типом short" + " равно " + youCool);
        long money = 912356789;
        System.out.println(money);
        System.out.println("Значение переменной money" + " с типом long" + " равно " + money);
        float home = 7.5443f;
        System.out.println(home);
        System.out.println("Значение переменной home" + " с типом float" + " равно " + home);
        double key = 89.3857357f;
        System.out.println(key);
        System.out.println("Значение переменной key" + " с типом double" + " равно " + key);
        System.out.println("Задача 2.");
        float q = 27.12f;
        System.out.println("Тип переменной для " + q + " - float");
        long w = 987678965549L;
        System.out.println("Тип переменной для " + w + " - long");
        double e = 2.786;
        System.out.println("Тип переменной для " + e + " - double");
        int r = 569;
        System.out.println("Тип переменной для " + r + " - int");
        short t = -159;
        System.out.println("Тип переменной для " + t + " - short");
        int y = 27897;
        System.out.println("Тип переменной для " + y + " - int");
        byte u = 67;
        System.out.println("Тип переменной для " + u + " - byte");
        System.out.println("Задача 3.");
        byte teacher1 = 23;
        byte teacher2 = 27;
        byte teacher3 = 30;
        int totalStudents = teacher1 + teacher2 + teacher3;
        System.out.println("Всего учеников в трех классах - " + totalStudents);
        int paper = 480;
        System.out.println("Всего закуплено бумаги - " + paper + " листов");
        int paperOfPerson = paper / totalStudents;
        System.out.println("На каждого ученика рассчитано " + paperOfPerson + " листов бумаги.");
        System.out.println("Задача 4.");
        byte bottlesInTwoMinutes = 16;
        byte time = 2;
        int bottlesInOneMinutes = bottlesInTwoMinutes / time;
        System.out.println("Производительность машины для изготовления бутылок — " + bottlesInOneMinutes + " бутылок за минуту.");
        int bottles20 = bottlesInOneMinutes * 20;
        System.out.println("За 20 минут машина произвела " + bottles20 + " штук бутылок.");
        int day = 24 * 60;
        int bottlesDay = bottlesInOneMinutes * day;
        System.out.println("За сутки машина произвела " + bottlesDay + " штук бутылок.");
        int day3 = day * 3;
        int bottlesDay3 = bottlesInOneMinutes * day3;
        System.out.println("За 3 дня машина произвела " + bottlesDay3 + " штук бутылок.");
        int month = day * 31;
        int bottlesMonth = bottlesInOneMinutes * month;
        System.out.println("За месяц машина произвела " + bottlesMonth + " штук бутылок.");
        System.out.println("Задача 5.");
        byte total = 120;
        byte white = 2;
        byte brown = 4;
        int class1 = white + brown;
        System.out.println("Для покраски одного класса необходимо " + class1 + " банок краки.");
        int schoolClass = total / class1;
        System.out.println("В школе " + schoolClass + " классов, которые необходимо покрасить.");
        int whiteDue = white * schoolClass;
        int brownDue = brown * schoolClass;
        System.out.println("В школе, где " + schoolClass + " классов, нужно " + whiteDue + " банок белой краски и " + brownDue + " банок коричневой краски.");
        System.out.println("Задача 6.");
        int bananas = 5 * 80;
        int milk = 2 * 105;
        int iceCream = 2 * 100;
        int eggs = 4 * 70;
        int weight = bananas + milk + iceCream + eggs;
        System.out.println("Вес спортзавтрака составляет " + weight + " грамм");
        float kg =  weight / 1000F;
        System.out.println("Вес спортзавтрака составляет " + kg + " килограмм");
        System.out.println("Задача 7.");
        int gram = 7 * 1000;
        System.out.println("Спортсмену нужно сбросить 7 кг или " + gram + " грамм");
        int loss250 = gram / 250;
        System.out.println("Если он будет терять 250 грамм каждый день, то достигнет цели через " + loss250 + " дней");
        int loss500 = gram / 500;
        System.out.println("Если он будет терять 500 грамм каждый день, то достигнет цели через " + loss500 + " дней");
        System.out.println("Чтобы добиться результата похудения, в среднем может потребоваться от " + loss500 + " до " + loss250 + " дней");
        System.out.println("Задача 8.");
        int masha = 67760;
        double masha10 = masha * 0.1;
        double mashaSalary = masha + masha10;
        int mashaYears = masha * 12;
        double mashaNewYears = mashaSalary * 12;
        double mashaIncreased = mashaNewYears - mashaYears;
        System.out.println("Маша теперь получает " + mashaSalary + " рублей. Годовой доход вырос на " + mashaIncreased + " рублей.");
        int denis = 83690;
        double denis10 = denis * 0.1;
        double denisSalary = denis + denis10;
        int denisYears = denis * 12;
        double denisNewYears = denisSalary * 12;
        double denisIncreased = denisNewYears - denisYears;
        System.out.println("Денис теперь получает " + denisSalary + " рублей. Годовой доход вырос на " + denisIncreased + " рублей.");
        int kristi = 76230;
        double kristi10 = kristi * 0.1;
        double kristiSalary = kristi + kristi10;
        int kristiYears = kristi * 12;
        double kristiNewYears = kristiSalary * 12;
        double kristiIncreased = kristiNewYears - kristiYears;
        System.out.println("Кристина теперь получает " + kristiSalary + " рублей. Годовой доход вырос на " + kristiIncreased + " рублей.");
    }
}